name: "lint helm v3"
description: "lints a helm chart"
author: "eDACT"
inputs:
  working_directory:
    description: "working directory the action should be performed in"
    default: ".deploy"
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
