name: "Lint PHP"
description: "Lint PHP Project using PHP CS-Fixer."
inputs:
  working_directory:
    description: "Working directory in which to run the linter."
    required: false
    default: "src"

runs:
  using: "composite"
  steps:
    - name: Putting src/composer.json in output variable
      shell: bash
      id: set_var
      run: |
        content=`cat src/composer.json`
        # the following lines are only required for multi line json
        content="${content//'%'/'%25'}"
        content="${content//$'\n'/'%0A'}"
        content="${content//$'\r'/'%0D'}"
        # end of optional handling for multi line json
        echo "::set-output name=composerJson::$content"

    - name: Evaluating edact package versions
      shell: bash
      run: |
        #
        echo "${{fromJson(steps.set_var.outputs.composerJson.require)}}"
        echo "${{fromJson(steps.set_var.outputs.composerJson).require.'edact/e3t-oas-components'}}"
        # if [[ "${{fromJson(steps.set_var.outputs.composerJson).require.edact/}}" != dist/* ]]; then
        #   echo "::error::The field 'main' in the package.json must point to the 'dist' folder!"
        #   exit 1
        # fi
    - name: install dependencies & run linter
      shell: bash
      run: |
        #
        # makes the script existing once an error occours
        set -euo pipefail

        # switch working directory
        cd ${{ inputs.working_directory }}

        echo "::group::Installing dependencies.."
        composer install --quiet
        echo "::endgroup::"

        echo "::group::Linting php project.."
        composer lint-dry
        echo "::endgroup::"
