name: "run docker compose"
description: "Logs into docker registry and runs docker compose up -d"
author: "eDACT"
inputs:
  file:
    description: "Compose file to run."
    default: "docker-compose.yml"
    required: false
  docker_registry_url:
    description: "URL of the docker registry, no trailing slashes"
    required: false
    default: "registry.edact.de"
  docker_registry_user:
    description: "user for registry"
    required: false
    default: "robot$publisher"
  docker_registry_token:
    description: "token for registry"
    required: true
  healthcheck_command:
    description: "Bash command to execute until true."
    required: false
    default: 1 == 1
  healthcheck_offset:
    description: "Amount of seconds to wait before executing the first healthcheck."
    required: false
    default: "10"
  healthcheck_limit:
    description: "Amount of maximum retries of the healthcheck."
    required: false
    default: "12"
  healthcheck_timeout:
    description: "Amount of seconds to wait before retrying a healthcheck."
    required: false
    default: "5"

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        echo "${{ inputs.docker_registry_token }}" | docker login -u '${{ inputs.docker_registry_user }}' --password-stdin ${{ inputs.docker_registry_url }}

        docker compose --file ${{ inputs.file }} up --detach --quiet-pull

        if [["${{ inputs.healthcheck_timeout }}" > '0']]; then
          echo "Waiting ${{ inputs.healthcheck_timeout}} seconds before executing first healthcheck.."
          sleep ${{ inputs.healthcheck_timeout }}
        fi

        RETRIES=0

        while ! ${{ inputs.healthcheck }}; do
            if [["$RETRIES" > "${{ inputs.healthcheck_limit }}"]]; then
              echo "::error::Limit of ${{ inputs.healthcheck_limit }} reached."
            fi

            echo >&2 'Health check failed, retrying in ${{ inputs.healthcheck_timeout }} seconds..'
            sleep ${{ inputs.healthcheck_timeout }}

            RETRIES=$RETRIES+1
        done

        echo >&2 'Health check succeeded.'
