name: "Lint PHP"
description: "Lint PHP Project using PHP CS-Fixer."
runs:
  using: "composite"
  steps:
    - name: install project
      shell: bash
      run: |
        cd src
        composer install -q
        composer lint-dry
    # - name: lint project
    #   shell: bash
    #   run:
