name: "run newman cli"
description: "Runs newman cli for a given postman collection."
author: "eDACT"
inputs:
  postman_token:
    description: "Postman API Token needed for fetching the collection."
    required: true
  postman_collection_id:
    description: "ID of the collection to run."
    required: true
  postman_collection_folder:
    description: "Folder name of the collection to run."
    required: true

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        #
        # makes the script existing once an error occours
        set -euo pipefail

        # install newman & html reporter
        echo "::group::Installing newman cli.."
        npm install newman newman-reporter-htmlextra --global --quiet
        echo "::endgroup::"

        echo "::group::Downloading postman collection.."
        curl https://api.getpostman.com/collections/${{ inputs.postman_collection_id }}?apikey=${{ inputs.postman_token }} --output collection.json
        echo "::endgroup::"

        # run newman
        echo "::group::Running integration tests.."
        newman run https://api.getpostman.com/collections/${{ inputs.postman_collection_id }}?apikey=${{ inputs.postman_token }} \
            --env-var baseUrl=localhost:8080 \
            $( [ "${{ inputs.postman_collection_folder }}" != "" ] && printf %s "--folder ${{ inputs.postman_collection_folder }}" ) \
            --reporters cli,htmlextra --reporter-htmlextra-export ./newman/report.html
        echo "::endgroup::"
