name: "publish npm package"
description: "publish npm package"
author: "eDACT"
inputs:
  package_version:
    description: "version the package should get"
    required: true

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        # makes the script existing once an error occours
        set -euo pipefail

        # set version
        npm version ${{ inputs.package-version }} --no-git-tag-version --force

        # publish package to registry
        echo "::group::Publish package"
        # TODO: remove --registry
        npm publish --registry=https://npm.pkg.github.com
        echo "::endgroup::"
