name: "publish npm package"
description: "Publishes npm package."
author: "eDACT"
inputs:
  package_version:
    description: "Version the package should get."
    required: true

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        #
        # makes the script existing once an error occours
        set -euo pipefail

        # set version
        npm version ${{ inputs.package_version }} --no-git-tag-version --force

        # publish package to registry
        echo "::group::Publishing package to npm registry.."
        npm publish
        echo "::endgroup::"
