name: "publish npm package"
description: "Publishes npm package."
author: "eDACT"
inputs:
  npm_registry_url:
    description: "URL of the npm registry, no trailing slashes."
    default: "https://npm.pkg.github.com"
    required: false
  package_version:
    description: "Version the package should get."
    required: true

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        #
        # makes the script existing once an error occours
        set -euo pipefail

        # set version
        npm version ${{ inputs.package_version }} --no-git-tag-version --force

        # publish package to registry
        echo "::group::Publishing package to npm registry.."
        # TODO: eigentlich braucht man das --registry nicht, das kann also mal wieder weg
        npm publish --registry=${{ inputs.npm_registry_url }}
        echo "::endgroup::"
