name: "compute version strings"
description: "computes version strings based on GITHUB_REF for major, minor and patch version available in steps.<step_id>.outputs.version_{major/minor/patch}"
author: "eDACT"
outputs:
  version_patch:
    description: "Patch Version"
    value: ${{ steps.versions.outputs.version_patch }}
  version_minor:
    description: "Minor Version"
    value: ${{ steps.versions.outputs.version_minor }}
  version_major:
    description: "Major Version"
    value: ${{ steps.versions.outputs.version_major }}

runs:
  using: "composite"
  steps:
    - shell: bash
      id: versions
      run: |
        # makes the script existing once an error occours
        set -euo pipefail

        # compute values
        VERSION=$(echo '${{ github.ref }}'| cut -d'/' -f 3)
        VERSION=${VERSION#"v"}
        MINOR=$(echo $VERSION| cut -d'.' -f 1,2)
        MAJOR=$(echo $VERSION| cut -d'.' -f 1)

        # set output for github actions
        echo "::set-output name=version_major::${MAJOR}"
        echo "::set-output name=version_minor::${MINOR}"
        echo "::set-output name=version_patch::${VERSION}"
        echo $VERSION
        echo $MINOR
        echo $MAJOR
