name: "Create version file"
description: "Creates version file containing commit information."
inputs:
  path:
    description: "Path to the version file"
    required: false
    default: "version.json"

runs:
  using: "composite"
  steps:
    - name: generate json file with commit details
      shell: bash
      run: |
        #
        # makes the script existing once an error occours
        set -euo pipefail

        echo '{ "commit": "${{ github.sha }}","ref": "${{ github.ref }}","base_ref": "${{ github.base_ref }}" }' > ${{ inputs.path }}
