name: "check npm package"
description: "Checks npm package for errors that should not be merged into main by running tests and linters."
author: "eDACT"

runs:
  using: "composite"
  steps:
    - name: Putting package.json in output variable
      shell: bash
      id: set_var
      run: |
        content=`cat package.json`
        # the following lines are only required for multi line json
        content="${content//'%'/'%25'}"
        content="${content//$'\n'/'%0A'}"
        content="${content//$'\r'/'%0D'}"
        # end of optional handling for multi line json
        echo "::set-output name=packageJson::$content"

    - name: Evaluating npm entrypoint
      shell: bash
      run: |
        #
        if [[ "${{fromJson(steps.set_var.outputs.packageJson).main}}" != dist/* ]]; then
          echo "::error title=Invalid package entrypoint::The field 'main' in the package.json must point to the 'dist/*' folder!"
          exit 1
        fi

    - shell: bash
      run: |
        #
        # makes the script existing once an error occours
        set -euo pipefail

        # install dependencies
        echo "::group::Installing dependencies.."
        npm install
        echo "::endgroup::"

        # run tests specified in package.json
        echo "::group::Running tests.."
        npm run test --if-present
        echo "::endgroup::"

        # set mode to production
        export NODE_ENV="production"

        # lint project
        echo "::group::Running linter.."
        npm run lint --if-present --no-fix
        echo "::endgroup::"
