name: "create .npmrc file"
description: "Creates .npmrc file needed for installing npm packages from private registries."
author: "eDACT"
inputs:
  npm_registry_url:
    description: "URL of the npm registry, no trailing slashes."
    default: "npm.pkg.github.com"
    required: false
  npm_scope:
    description: "Package scope for the private package registry."
    default: "@edact"
    required: false
  npm_token:
    description: "Authentication token for the private registry."
    required: true

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        #
        # makes the script existing once an error occours
        set -euo pipefail

        printf "${{ inputs.npm_scope }}:registry=https://${{ inputs.npm_registry_url }}/ \n //${{ inputs.npm_registry_url }}/:_authToken=${{ inputs.npm_token }}"> .npmrc
