name: "create auth.json file for composer"
description: "Creates auth.json file needed for private package registries in composer."
author: "eDACT"
inputs:
  registry_url:
    description: "URL of the registry, no trailing slashes."
    default: "github.com"
    required: false
  location:
    description: "Location for generated file, no trailing slashes."
    default: src
    required: false
  deploy_token:
    description: "Deploy token for private package registries."
    required: true

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        #
        # makes the script existing once an error occours
        set -euo pipefail

        cd ./${{ inputs.location }}

        JSON_FMT='{"github-oauth":{"%s": "%s"} }\n'
        printf "$JSON_FMT" "${{ inputs.registry_url }}" "${{ inputs.deploy_token }}" > auth.json
