name: "build helm v3"
description: "Logs into a helm registry, builds and pushes a helm chart."
author: "eDACT"
inputs:
  helm_registry_url:
    description: "URL of the helm registry, no trailing slashes."
    default: ghcr.io/edact/helm
    required: true
  working_directory:
    description: "Working directory the action should be performed in."
    default: ".deploy"
    required: false
  chart_name:
    description: "Name of the helm chart."
    required: true
  chart_tags:
    description: "List of tags for the helm chart, seperated by comma."
    required: true
  helm_registry_user:
    description: "Username for the helm registry."
    default: "manuelottlik"
    required: true
  helm_registry_token:
    description: "Token / password of the username for the helm registry."
    required: true
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        #
        # makes the script existing once an error occours
        set -euo pipefail

        echo "::group::Downloading helm cli.."
        curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 > get_helm.sh
        chmod 700 get_helm.sh && ./get_helm.sh
        echo "::endgroup::"

        export HELM_EXPERIMENTAL_OCI=1

        # switch to working directory
        cd ${{ inputs.working_directory }}

        # log into helm registry
        echo "::group::Logging into helm registry.."
        helm registry login -u '${{ inputs.helm_registry_user }}' -p '${{ inputs.helm_registry_token }}' ${{ inputs.helm_registry_url }}
        echo "::endgroup::"

        # split chart tags in array
        chart_tags=$(echo '${{ inputs.chart_tags }}' | tr ", " "\n")

        # set tags
        echo "::group::Pushing helm chart.."
        for chart_tag in $chart_tags
        do
            helm package . --version ${chart_tag}
            helm push ${{ inputs.chart_name }}-${chart_tag}.tgz oci://${{ inputs.helm_registry_url}}/${{ github.repository }}
        done
        echo "::endgroup::"
