name: "build helm v3"
description: "builds and pushes a helm chart"
author: "eDACT"
inputs:
  helm_registry_url:
    description: "URL of the helm registry, no trailing slashes"
    default: registry.edact.de/helm
    required: true
  working_directory:
    description: "working directory the action should be performed in"
    default: ".deploy"
    required: false
  chart_name:
    description: "name of the chart"
    required: true
  chart_tags:
    description: "list of tags, seperated by comma"
    required: true
  helm_registry_user:
    description: "name of registry user"
    default: "robot$publisher"
    required: true
  helm_registry_token:
    description: "token of registry user"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
