name: "lint openapi specification"
description: "Lints a given openapi specification with spectral."
author: "eDACT"
inputs:
  input_path:
    description: "Path to file that should linted."
    required: false
    default: "src/public/openapi.yml"

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        #
        # makes the script existing once an error occours
        set -euo pipefail

        if [ ! -f "${{ inputs.input_path }}" ]; then
            echo "::error::${{ inputs.input_path }} does not exist!"
            exit 1
        fi

        # install
        echo "::group::Installing linter.."
        npm i @stoplight/spectral@^5.0.0 --global --quiet
        echo "::endgroup::"

        # lint
        echo "::group::Linting openapi specification.."
        spectral lint ${{ inputs.input_path }} --skip-rule oas3-unused-components-schema
        echo "::endgroup::"
