name: "lint openapi file"
description: "lints a given openapi file with spectral"
author: "eDACT"
inputs:
  input_path:
    description: "path to file that should linted"
    required: false
    default: "src/public/openapi.yml"

runs:
  # using: "docker"
  # image: "Dockerfile"
  using: "composite"
  steps:
    - shell: bash
      run: |
        # makes the script existing once an error occours
        set -euo pipefail

        if [ ! -f "$INPUT_INPUT_PATH" ]; then
            echo "::error::$INPUT_INPUT_PATH does not exist!"
            exit 1
        fi

        # install
        npm i @stoplight/spectral@^5.0.0 --global --quiet

        # lint
        spectral lint ${INPUT_INPUT_PATH} --skip-rule oas3-unused-components-schema
