name: "lint openapi file"
description: "lints a given openapi file with spectral"
author: "eDACT"
inputs:
  input_path:
    description: "path to file that should linted"
    required: false
    default: "src/public/openapi.yml"

runs:
  using: "composite"
  steps:
    - shell: bash
      run: sh entrypoint.sh
