name: build latest
on:
  workflow_call:
    secrets:
      READ_TOKEN:
        required: true
      EPR_TOKEN:
        required: true

jobs:
  build-docker:
    name: build docker image
    runs-on: ubuntu-latest

    steps:
      - name: Fetching repository
        uses: actions/checkout@main
        with:
          submodules: true
          token: ${{ secrets.READ_TOKEN }}

      - name: Bundling openapi-internal.yml
        uses: edact/o3t-github-actions/bundle-openapi-spec@main
        with:
          output_path: src/public/openapi-internal.yml
          dereference: true
          delete_files: false

      - name: Bundling openapi.yml
        uses: edact/o3t-github-actions/bundle-openapi-spec@main

      - name: create auth.json file
        uses: edact/o3t-github-actions/create-authjson-file@main
        with:
          deploy_token: ${{ secrets.READ_TOKEN }}

      - name: Creating version.json file
        uses: edact/o3t-github-actions/create-version-file@main

      - name: Building docker image
        uses: edact/o3t-github-actions/build-docker-image@main
        with:
          image_name: ${{ github.event.repository.name }}
          image_tags: latest
          docker_registry_token: ${{ secrets.EPR_TOKEN }}
