name: build version
on:
  workflow_call:
    secrets:
      READ_TOKEN:
        required: true
      EPR_TOKEN:
        required: true

jobs:
  build-docker:
    name: build docker image
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@main
        with:
          submodules: true
          token: ${{ secrets.READ_TOKEN }}

      - name: bundle fully derefenced openapi
        uses: edact/o3t-github-actions/bundle-openapi-spec@main
        with:
          output_filename: openapi-internal.yml
          dereference: true
          delete_files: false

      - name: bundle default openapi
        uses: edact/o3t-github-actions/bundle-openapi-spec@main

      - name: create auth.json file
        uses: edact/o3t-github-actions/create-authjson-file@main
        with:
          deploy_token: ${{ secrets.READ_TOKEN }}

      - name: create version file
        uses: edact/o3t-github-actions/create-version-file@main

      - name: compute version strings
        uses: ./.github/actions/compute-version-strings
        id: versionGetter

      - name: build docker image
        uses: edact/o3t-github-actions/build-docker-image@main
        with:
          image_name: ${{ github.event.repository.name }}
          image_tags: stable, ${{ steps.versionGetter.outputs.version_minor }}, ${{ steps.versionGetter.outputs.version_major }}
          docker_registry_token: ${{ secrets.EPR_TOKEN }}
