name: build version
on:
  workflow_call:
    secrets:
      READ_TOKEN:
        required: true
      EPR_TOKEN:
        required: true

jobs:
  build-docker:
    name: build docker image
    runs-on: ubuntu-latest

    steps:
      - name: Fetching repository
        uses: actions/checkout@main

      - name: Creating auth.json file
        uses: edact/o3t-github-actions/create-authjson-file@main
        with:
          deploy_token: ${{ secrets.READ_TOKEN }}

      - name: Installing composer dependencies
        run: |
          cd src
          composer install

      - name: Bundling openapi-internal.yml
        uses: edact/o3t-github-actions/bundle-openapi-spec@main
        with:
          output_path: src/public/openapi-internal.yml
          dereference: true
          delete_files: false

      - name: Bundling openapi.yml
        uses: edact/o3t-github-actions/bundle-openapi-spec@main

      - name: create auth.json file
        uses: edact/o3t-github-actions/create-authjson-file@main
        with:
          deploy_token: ${{ secrets.READ_TOKEN }}

      - name: Creating version.json file
        uses: edact/o3t-github-actions/create-version-file@main
        with:
          path: "src/public/version.json"

      - name: Computing version strings
        uses: edact/o3t-github-actions/compute-version-strings@main
        id: versionGetter

      - name: Building docker image
        uses: edact/o3t-github-actions/build-docker-image@main
        with:
          image_name: ${{ github.event.repository.name }}
          image_tags: stable, ${{ steps.versionGetter.outputs.version_minor }}, ${{ steps.versionGetter.outputs.version_major }}
          docker_registry_token: ${{ secrets.EPR_TOKEN }}
