name: build feature
on:
  workflow_call:
    inputs:
      type:
        description: "feature/latest/version"
        type: string
        required: true
    secrets:
      READ_TOKEN:
        required: true
      EPR_TOKEN:
        required: true

jobs:
  build-docker:
    name: build docker image
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@main
        with:
          submodules: true
          token: ${{ secrets.READ_TOKEN }}

      - name: bundle fully derefenced openapi
        uses: edact/o3t-github-actions/bundle-openapi@main
        with:
          output_filename: openapi-internal.yml
          dereference: true
          delete_files: false

      - name: bundle default openapi
        uses: edact/o3t-github-actions/bundle-openapi@main

      - name: create auth.json file
        uses: edact/o3t-github-actions/create-authjson-file@main
        with:
          location: src
          deploy_token: ${{ secrets.READ_TOKEN }}

      - name: build docker image
        uses: edact/o3t-github-actions/build-docker-image@main
        if: ${{ inputs.type == 'feature' }}
        with:
          image_name: ${{ github.event.repository.name }}
          image_tags: feature
          docker_registry_token: ${{ secrets.EPR_TOKEN }}

      - name: build docker image
        uses: edact/o3t-github-actions/build-docker-image@main
        if: ${{ inputs.type == 'latest' }}
        with:
          image_name: ${{ github.event.repository.name }}
          image_tags: latest
          docker_registry_token: ${{ secrets.EPR_TOKEN }}

      - name: compute version strings
        uses: ./.github/actions/compute-version-strings
        if: ${{ inputs.type == 'version' }}
        id: versionGetter

      - name: build docker image
        uses: edact/o3t-github-actions/build-docker-image@main
        if: ${{ inputs.type == 'version' }}
        with:
          image_name: ${{ github.event.repository.name }}
          image_tags: stable, ${{ steps.versionGetter.outputs.version_minor }}, ${{ steps.versionGetter.outputs.version_major }}
          docker_registry_token: ${{ secrets.EPR_TOKEN }}
