name: build feature deployment
on:
  workflow_call:
    secrets:
      HELM_REGISTRY_TOKEN:
        description: "eDACT Helm Registry Token"
        required: true
jobs:
  push-helm:
    name: push helm charts
    runs-on: ubuntu-latest
    steps:
      - name: Fetching repository
        uses: actions/checkout@main

      - name: Linting helm chart
        uses: edact/o3t-github-actions/lint-helm-chart@feature/change-registry

      - name: Building helm chart
        uses: edact/o3t-github-actions/build-helm-chart@feature/change-registry
        with:
          chart_name: ${{ github.event.repository.name }}
          chart_tags: 0.0.0-feature
          helm_registry_token: ${{ secrets.HELM_REGISTRY_TOKEN }}
