name: build latest deployment
on:
  workflow_call:
    secrets:
      EHR_TOKEN:
        description: "eDACT Helm Registry Token"
        required: true

jobs:
  push-helm:
    name: push helm charts
    runs-on: ubuntu-latest
    steps:
      - name: Fetching repository
        uses: actions/checkout@main

      - name: Building helm chart
        uses: edact/o3t-github-actions/build-helm-chart@main
        with:
          chart_name: ${{ github.event.repository.name }}
          chart_tags: 0.0.0-latest
          helm_registry_token: ${{ secrets.EHR_TOKEN }}
