name: pull request
on:
  workflow_call:
    inputs:
      POSTMAN_COLLECTION_ID:
        description: "ID of the postman collection that contains the integration tests."
        type: string
        required: true
    secrets:
      READ_TOKEN:
        required: true
      EPR_TOKEN:
        description: "eDACT Package Registry Token"
        required: true
      POSTMAN_TOKEN:
        description: "Postman API Token"
        required: true
jobs:
  lint-php:
    name: lint php
    runs-on: ubuntu-latest
    steps:
      - name: Fetching repository
        uses: actions/checkout@main

      - name: Creating auth.json file
        uses: edact/o3t-github-actions/create-authjson-file@main
        with:
          deploy_token: ${{ secrets.READ_TOKEN }}

      - name: Linting php project
        uses: edact/o3t-github-actions/lint-php-project@main

  lint-helm:
    name: lint helm
    runs-on: ubuntu-latest
    steps:
      - name: Fetching repository
        uses: actions/checkout@main

      - name: Linting helm chart
        uses: edact/o3t-github-actions/lint-helm-chart@main

  lint-oas:
    name: lint oas
    runs-on: ubuntu-latest
    steps:
      - name: Fetching repository
        uses: actions/checkout@main
        with:
          submodules: true
          token: ${{ secrets.READ_TOKEN }}

      - name: Bundling openapi.yml
        uses: edact/o3t-github-actions/bundle-openapi-spec@main

      - name: Uploading bundled openapi.yml
        uses: actions/upload-artifact@main
        with:
          name: bundled-openapi
          path: src/public/openapi.yml

      - name: Linting openapi specification
        uses: edact/o3t-github-actions/lint-openapi-spec@main

  run-integration-tests:
    name: run integration tests
    runs-on: ubuntu-latest
    needs:
      - lint-helm
      - lint-oas
      - lint-php
    steps:
      - name: Fetching repository
        uses: actions/checkout@main
        with:
          submodules: true
          token: ${{ secrets.READ_TOKEN }}

      - name: Creating auth.json file
        uses: edact/o3t-github-actions/create-authjson-file@main
        with:
          deploy_token: ${{ secrets.READ_TOKEN }}

      - name: Bundling openapi-internal.yml
        uses: edact/o3t-github-actions/bundle-openapi-spec@main
        with:
          output_path: src/public/openapi-internal.yml
          dereference: true
          delete_files: false

      - name: Bundling openapi.yml
        uses: edact/o3t-github-actions/bundle-openapi-spec@main

      - name: Running docker compose setup
        uses: edact/o3t-github-actions/run-docker-compose@add-gatekeeper
        with:
          docker_registry_token: ${{ secrets.EPR_TOKEN }}
          file: docker-compose-ci.yml
          healthcheck_command: curl --silent --fail localhost:8080/e3t/health

      - name: Running integration tests
        uses: edact/o3t-github-actions/run-newman-cli@main
        with:
          postman_token: ${{ secrets.POSTMAN_TOKEN }}
          postman_collection_id: ${{ inputs.POSTMAN_COLLECTION_ID }}

      - name: Uploading newman report
        uses: actions/upload-artifact@main
        if: always()
        with:
          name: newman-report
          path: ./newman/report.html
