name: build feature
on:
  workflow_call:
    secrets:
      READ_TOKEN:
        required: true
      EPR_TOKEN:
        required: true

jobs:
  lint-php:
    name: lint php
    runs-on: ubuntu-latest
    steps:
      - name: Fetching repository
        uses: actions/checkout@main

      - name: Creating auth.json file
        uses: edact/o3t-github-actions/create-authjson-file@main
        with:
          deploy_token: ${{ secrets.READ_TOKEN }}

      - name: Linting php code
        uses: edact/o3t-github-actions/lint-php-project@main

  lint-oas:
    name: lint oas
    runs-on: ubuntu-latest
    steps:
      - name: Fetching repository
        uses: actions/checkout@main

      - name: Installing composer dependencies
        run: |
          cd src
          composer install

      - name: Bundling openapi.yml
        uses: edact/o3t-github-actions/bundle-openapi-spec@main

      - name: Uploading bundled openapi.yml
        uses: actions/upload-artifact@main
        with:
          name: bundled-openapi
          path: src/public/openapi.yml

      - name: Linting openapi specification
        uses: edact/o3t-github-actions/lint-openapi-spec@main

  build-docker:
    name: build docker image
    runs-on: ubuntu-latest
    needs:
      - lint-helm
      - lint-oas
      - lint-php
    steps:
      - name: Fetching repository
        uses: actions/checkout@main

      - name: Bundling openapi-internal.yml
        uses: edact/o3t-github-actions/bundle-openapi-spec@main
        with:
          output_path: src/public/openapi-internal.yml
          dereference: true
          delete_files: false

      - name: Bundling openapi.yml
        uses: edact/o3t-github-actions/bundle-openapi-spec@main

      - name: Creating auth.json file
        uses: edact/o3t-github-actions/create-authjson-file@main
        with:
          deploy_token: ${{ secrets.READ_TOKEN }}

      - name: Creating version.json file
        uses: edact/o3t-github-actions/create-version-file@main

      - name: Building docker image
        uses: edact/o3t-github-actions/build-docker-image@improvements
        with:
          image_name: ${{ github.event.repository.name }}
          image_tags: feature
          docker_registry_token: ${{ secrets.EPR_TOKEN }}
          use_cache: true
