name: "enforce repository settings"
on:
  # push:
  workflow_dispatch:
  schedule:
    - cron: "5 5 * * *"

jobs:
  enforce-repo-settings:
    runs-on: ubuntu-latest
    steps:
      - name: Fetching repository
        uses: actions/checkout@main

      - name: Enforcing repo settings
        uses: ./enforce-repo-settings
        with:
          api-token: ${{ secrets.API_TOKEN }}
