name: publish npm package
on:
  workflow_call:
    secrets:
      NPM_REGISTRY_TOKEN:
        description: "GitHub Package Registry Token"
        required: true

jobs:
  build-npm:
    name: Building and pushing npm package
    runs-on: ubuntu-latest
    steps:
      - name: Fetching repository
        uses: actions/checkout@main

      - name: Creating .npmrc file
        uses: edact/o3t-github-actions/create-npmrc-file@main
        with:
          npm_token: ${{ secrets.NPM_REGISTRY_TOKEN }}

      - name: Computing version strings
        uses: edact/o3t-github-actions/compute-version-strings@main
        id: versionGetter

      - name: Caching node_modules
        uses: actions/cache@main
        with:
          path: node_modules
          key: cache-node-modules-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            cache-node-modules-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: Building project
        uses: edact/o3t-github-actions/build-npm-package@main

      - name: Publishing npm package
        uses: edact/o3t-github-actions/publish-npm-package@main
        with:
          package_version: ${{steps.versionGetter.outputs.version_patch}}
