name: pull request
on:
  workflow_call:
    secrets:
      NPM_REGISTRY_TOKEN:
        description: "GitHub Package Registry Token"
        required: true

jobs:
  run-tests-and-linting:
    name: tests & linting
    runs-on: ubuntu-latest
    steps:
      - name: Fetching repository
        uses: actions/checkout@main

      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: npm

      - name: Creating .npmrc file
        uses: edact/o3t-github-actions/create-npmrc-file@main
        with:
          npm_token: ${{ secrets.NPM_REGISTRY_TOKEN }}

      # - name: Caching node_modules
      #   uses: actions/cache@main
      #   with:
      #     path: node_modules
      #     key: cache-node-modules-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      #     restore-keys: |
      #       cache-node-modules-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: Running tests & linter
        uses: edact/o3t-github-actions/check-npm-package@main

      - name: Building project
        uses: edact/o3t-github-actions/build-npm-package@main
  try-thing:
    name: try thing
    runs-on: ubuntu-latest
    steps:
      - name: Fetching repository
        uses: actions/checkout@main
      - id: set_var
        run: |
          content=`cat package.json`
          # the following lines are only required for multi line json
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          # end of optional handling for multi line json
          echo "::set-output name=packageJson::$content"
      - run: |
          echo "${{fromJson(steps.set_var.outputs.packageJson).main}}"
          if [[ "${{fromJson(steps.set_var.outputs.packageJson).main}}" != dist/* ]]; then
            echo "we got it wrong"
          fi
